version: 0.0
os: linux
runas: root
files:
  - source: /
    destination: /home/ubuntu/node-express-realworld-example-app/
    overwrite: true
file_exists_behavior: OVERWRIT
   
hooks:
   ApplicationStop:
     - location: scripts/stop_script.sh
       timeout: 30
       
   ApplicationStart:
     - location: scripts/start_script.sh
       timeout: 30
