version: 0.2

run-as: root

env:
  parameter-store:
    a: "/pankaj/mongo-url"

phases:

  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
  build:
    commands:
      - echo PANKAJ_URI = $a > .env
      - echo Building ...

  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - '**/*'
    - echo Uploaded Artifacts
